services:
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      target: dev
      args:
        NODE_VERSION: 23.10.0
        WWWUSER: ${WWWUSER:-1000}
        WWWGROUP: ${WWWGROUP:-1000}
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    depends_on:
      - db
    networks:
      - chat-dev
    command: >
      sh -c "
        if [ ! -d 'node_modules' ] || [ ! -f 'node_modules/.package-lock.json' ] || [ package-lock.json -nt node_modules/.package-lock.json ]; then
          npm ci && touch node_modules/.package-lock.json && cp package-lock.json node_modules/.package-lock.json
        fi
        npm run dev
      "
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: 16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-dev

networks:
  chat-dev:
    driver: bridge

volumes:
  node_modules:
  postgres_data:
