services:
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      target: dev
      args:
        NODE_VERSION: 23.10.0
    environment:
      NODE_ENV: development
      WWWUSER: "${WWWUSER:-1000}"
      WWWGROUP: "${WWWGROUP:-1000}"
      TZ: ${APP_TIMEZONE:-Asia/Tokyo}
    ports:
      - 3000:3000
    volumes:
      - .:/src
    depends_on:
      - db
    networks:
      - chat-dev

  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: 16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      TZ: ${POSTGRES_TIMEZONE:-Asia/Tokyo}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-dev

networks:
  chat-dev:
    driver: bridge

volumes:
  postgres_data:
